### ISSUE TITLE
Cannot import _example

### ISSUE THREAD

**Issue by dmopalmer** [yanqd0/swig-python-demo#1] opened 2022-08-11 21:59 UTC
Under windows, `pip install` gives a library that doesn't import successfully.

```
----> 1 import example._example

File ~\Anaconda3\envs\test\lib\site-packages\example\__init__.py:3, in <module>
      1 """ A Python demo for SWIG """
----> 3 from .example import (
      4     cvar,
      5     fact,
      6     get_time,
      7     my_mod,
      8 )
      9 from .stl_example import (
     10     Int2strMap,
     11     Str2intMap,
   (...)
     14     vector_int2str,
     15 )
     16 from ._meta import (
     17     __author__,
     18     __email__,
   (...)
     22     __version__,
     23 )

File ~\Anaconda3\envs\test\lib\site-packages\example\example.py:13, in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _example
     14 else:
     15     import _example

ImportError: cannot import name '_example' from partially initialized module 'example' (most likely due to a circular import) (C:\Users\150772\Anaconda3\envs\test\lib\site-packages\example\__init__.py)
```

It appears that the binary library _example isn't generated or isn't installed.

```
$ ls ~/Anaconda3/envs/test/lib/site-packages/example
__init__.py  __pycache__/  _meta.py  example.py  stl_example.py
```

Even though it does seem to be generated in the build directory:
```
$ ls notmine/swig-python-demo/build/lib.win-amd64-3.10/
_example.cp310-win_amd64.pyd*  _stl_example.cp310-win_amd64.pyd*  example/
```

System details: 
Windows 10 21H2
Python 3.10.4
swig version 4.0.2 installed with Anaconda
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64

**Comment by yanqd0** [comment] 2022-08-23 07:28
I am not working on Windows, hard to reproduce that. But I think the issue is in packaging.

It will be fixed later.

**Closed as completed** 2022-08-23 07:33 UTC

**Comment by dmopalmer** [comment] 2022-08-23 16:48
This did not fix the problem.  After 
```
pip uninstall swig-example-demo
git clean -f -x -d
git pull
pip install --upgrade .
```

I get the same errors when I try to run it.  (I am using a Mac this time, so it is a Unix).  The file tree as installed is:
```
tree ~/Anaconda3/envs/test/lib/python3.10/site-packages/example
/Users/palmer/Anaconda3/envs/test/lib/python3.10/site-packages/example
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-310.pyc
│   ├── _meta.cpython-310.pyc
│   ├── example.cpython-310.pyc
│   └── stl_example.cpython-310.pyc
├── _meta.py
├── example.py
└── stl_example.py

1 directory, 8 files
```

Do I have to run the makefile first?  I am still adapting it to my system.  One tip from [StackOveflow](https://stackoverflow.com/questions/48838478/including-python-h-in-c-with-a-makefile) to find the directory paths automatically:

```
PY_CFLAGS  := $(shell python3-config --cflags)
PY_LDFLAGS := $(shell python3-config --ldflags)
```

**Comment by yanqd0** [comment] 2022-09-02 09:01
~~In recent versions, you need to run `python setup.py build` first.~~

~~In old versions, I remember the `build_py` will be executed before installing.~~

I will update a new way to handle this later, thanks.

---

The 2 `so` files will be in `site-packages/`, not `site-packages/example/`.

**Comment by bradbell** [comment] 2023-09-15 12:28
I would like to Reopen this issue for the following reason,  (but cannot find the way to do so)  :

Execute the following commands in the top directory of a clean version of this repository:
```
pip install . --user
python
import example
```
The result on my machine is
```
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bradbell/trash/swig-python-demo.git/build/lib.linux-x86_64-cpython-311/example/__init__.py", line 3, in <module>
    from .example import (
  File "/home/bradbell/trash/swig-python-demo.git/build/lib.linux-x86_64-cpython-311/example/example.py", line 10, in <module>
    from . import _example
ImportError: cannot import name '_example' from partially initialized module 'example' (most likely due to a circular import) (/home/bradbell/trash/swig-python-demo.git/build/lib.linux-x86_64-cpython-311/example/__init__.py)
```

The reason for this problem is that the file
```
_example.cpython-311-x86_64-linux-gnu.so
```
has been installed in the ``site-packages`` directory instead of  ``site-packages/example`` director. Hence
``import _example`` would work, but the file ``example.py`` (generated by swig) is expecting ``from . import _example`` to work.

The version of setuptools and swig for the results above are as follows:
```
swig-python-demo.git>dnf info python-setup*
Last metadata expiration check: 0:01:19 ago on Sat 16 Sep 2023 05:27:42 AM PDT.
Installed Packages
Name         : python-setuptools-wheel
Version      : 65.5.1
Release      : 2.fc38
Architecture : noarch
...

swig-python-demo.git>dnf info swig
Last metadata expiration check: 0:02:02 ago on Sat 16 Sep 2023 05:27:42 AM PDT.
Installed Packages
Name         : swig
Version      : 4.1.1
Release      : 4.fc38
Architecture : x86_64
```
